# Generated by Django 4.2.2 on 2023-07-04 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failure_Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recovery_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rejection', models.DateField()),
                ('operating_time_mh', models.PositiveIntegerField()),
                ('failure_description', models.CharField(max_length=255)),
                ('used_spare_parts', models.TextField()),
                ('date_recovery', models.DateField()),
                ('downtime', models.PositiveIntegerField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_car', to='car_app.car')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_fluire_node', to='claims_app.failure_node')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_recovery_method', to='claims_app.recovery_method')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_service_company', to='car_app.service_company')),
            ],
            options={
                'ordering': ['-date_rejection'],
            },
        ),
    ]
